apiVersion: v1
kind: Service
metadata:
        name: formatter
spec:
        ports:
        - port: 8080
          targetPort: 8080
        selector:
                run: "formatter"
        type: ClusterIP


